name: fun_zippy
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  comment_tree: ^0.3.0
  country_code_picker: ^3.0.0
  country_codes: ^2.2.0
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.1.0
  flutter_html: any
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.7
  flutter_typeahead: ^4.8.0
  form_builder_validators: ^9.0.0
  geocoding: ^2.1.0
  geolocator: any
  get: ^4.6.5
  get_storage: ^2.1.1
  google_maps_flutter: ^2.5.0
  image_picker: any
  intl_phone_field: ^3.2.0
  linear_step_indicator: ^1.0.0+3
  pin_code_fields: ^8.0.1
  uuid: any
  carousel_slider: ^4.2.1
  http: ^1.1.0


dependency_overrides:
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
